#!/bin/bash

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness_percentage=$(( $brightness * 100 / $max_brightness ))
echo "$brightness_percentage%"